version: '3.4'

volumes:
  db-data:
    external: false

services:
  broker_swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /broker/openapi.json
    volumes:
      - ./broker/swagger/v1:/broker
    ports:
      - 8081:8080

  messagist_swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /messagist/openapi.json
    volumes:
      - ./messagist/swagger/v1:/messagist
    ports:
      - 8082:8080

  db:
    image: mariadb:10.0
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=broker_development
    volumes:
      - db-data:/var/lib/mysql

  broker_app:
    container_name: broker_app
    build: ./broker
    entrypoint: /app/bin/entrypoint.sh
    command: bundle exec puma -C /app/config/puma.rb
    environment:
      RAILS_ROOT: /app
      RAILS_ENV: development
      RAILS_DEV_CACHE: allowed
      ADMIN_TOKEN: 123o123t123u123s
      DATABASE_URL: mysql2://root:123123@db:3306/broker_app_development
      TEST_DATABASE_URL: mysql2://root:123123@db:3306/broker_app_test
      MESSAGIST_API_URL: http://messagist_app:3033/api/v1
      MESSAGIST_API_LOGIN: broker
      MESSAGIST_API_PASS: broker_pass
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3123}:3000"
    volumes:
      - ./broker:/app
    links:
      - db

  messagist_app:
    build: ./messagist
    command: bundle exec puma -C /config/puma.rb
    environment:
      APP_PORT: 3033
      SMTP_ADDRESS: mailcatcher
      SMTP_PORT: 1025
      API_LOGIN: broker
      API_PASS: broker_pass
      SLACK_API_TOKEN: ''
      SLACK_CHANNEL: ''
      RACK_ENV: development
    depends_on:
      - mailcatcher
    links:
      - mailcatcher
    ports:
      - 3033:3033

  mailcatcher:
    build: ./mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
