version: '3.4'

volumes:
  db-data:
    external: false

services:
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /broker/swagger.json
    volumes:
      - ./broker/swagger/v1:/broker
    ports:
      - 8081:8080

  db:
    image: mariadb:10.0
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=broker_development
    volumes:
      - db-data:/var/lib/mysql

  broker_app:
    build: ./broker
    entrypoint: /app/bin/entrypoint.sh
    command: bundle exec puma -C /app/config/puma.rb
    environment:
      RAILS_ROOT: /app
      RAILS_ENV: development
      ADMIN_TOKEN: 123o123t123u123s
      DATABASE_URL: mysql2://root:123123@db:3306/broker_development
      TEST_DATABASE_URL: mysql2://root:123123@db:3306/broker_test
    depends_on:
      - db
    ports:
      - "${APP_PORT:-3123}:3000"
    volumes:
      - ./broker:/app
    links:
      - db
